# Generated by Django 5.1.2 on 2024-11-04 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='SN',
            field=models.CharField(default='Default_SN', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='damage_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_damaged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='process_status',
            field=models.CharField(choices=[('sorting_test', 'Under Sorting Test'), ('basic_check', 'Under Basic Check'), ('fa_lab', 'To FA Lab')], default='New', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='feature1.category'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature1.layer')),
            ],
            options={
                'unique_together': {('layer', 'number')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feature1.position'),
        ),
        migrations.AddField(
            model_name='layer',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature1.rack'),
        ),
        migrations.AlterUniqueTogether(
            name='layer',
            unique_together={('rack', 'number')},
        ),
    ]
