# Generated by Django 5.1.2 on 2024-11-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature1', '0003_alter_product_sn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='position',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rack',
            name='number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
