# Generated by Django 5.1.2 on 2024-11-04 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature1', '0005_alter_product_category_alter_product_process_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feature1.category'),
        ),
    ]
