# Generated by Django 5.1.2 on 2024-11-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature1', '0007_alter_category_name_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='SN',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
