# Generated by Django 5.1.2 on 2024-11-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature1', '0008_alter_product_sn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='SN',
            field=models.CharField(default='1', max_length=100, unique=True),
        ),
    ]
