# Generated by Django 5.1.2 on 2024-11-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature1', '0009_alter_product_sn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='layer',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='position',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='SN',
            field=models.CharField(default='0000000000000', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PG520', 'PG520'), ('PG530', 'PG530')], default='PG520', max_length=20),
        ),
        migrations.AlterField(
            model_name='rack',
            name='number',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
