# Generated by Django 5.1.2 on 2024-11-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feature1", "0010_alter_category_name_alter_layer_number_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="layer",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="position",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="layer",
            constraint=models.UniqueConstraint(
                fields=("rack", "number"), name="unique_rack_layer"
            ),
        ),
        migrations.AddConstraint(
            model_name="position",
            constraint=models.UniqueConstraint(
                fields=("layer", "number"), name="unique_layer_position"
            ),
        ),
    ]
