# Generated by Django 5.1.2 on 2024-11-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feature1", "0011_alter_layer_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layer",
            name="number",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="position",
            name="number",
            field=models.IntegerField(),
        ),
    ]
