# Generated by Django 5.1.3 on 2024-11-13 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_initial'),
    ]

    operations = [
    ]
