# Generated by Django 5.1.3 on 2024-11-14 19:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_auto_20241113_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='damage_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_damaged',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_hot',
        ),
        migrations.RemoveField(
            model_name='producttask',
            name='result',
        ),
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Notes or description of the product'),
        ),
        migrations.AddField(
            model_name='product',
            name='priority_level',
            field=models.CharField(choices=[('normal', 'Normal'), ('hot', 'Hot'), ('zfa', 'ZFA')], default='normal', help_text='Indicates if the unit is Normal, Hot, or ZFA', max_length=10),
        ),
        migrations.AddField(
            model_name='producttask',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='producttask',
            name='result_choice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producttask',
            name='result_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='action',
            field=models.CharField(default='Default Action', help_text='Action to be performed in this task', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='result_choices',
            field=models.TextField(blank=True, help_text="Comma-separated choices for result options if result type is 'Choice'"),
        ),
        migrations.AddField(
            model_name='task',
            name='result_type',
            field=models.CharField(choices=[('text', 'Text'), ('choice', 'Choice')], default='text', help_text='Type of the result for this task', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='can_be_skipped',
            field=models.BooleanField(default=False, help_text='Indicates if the task can be skipped'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(help_text='Detailed description of the task'),
        ),
        migrations.CreateModel(
            name='ResultOfStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_result', models.TextField(blank=True, help_text='Summary of the results for this status', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_results', to='product_management.product')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_results', to='product_management.status')),
            ],
        ),
    ]
