# Generated by Django 5.1.3 on 2024-11-12 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_rename_process_status_product_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='position',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completion_result',
        ),
        migrations.AddField(
            model_name='status',
            name='order',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.layer')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.rack')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product_management.location'),
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_number', models.IntegerField()),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='product_management.layer')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.space'),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('rack', 'layer', 'space')},
        ),
    ]
