# Generated by Django 5.1.3 on 2024-11-16 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0005_remove_producttask_result_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='task',
            name='note',
            field=models.TextField(blank=True, help_text='User can write down some notes on this task', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='SN',
            field=models.CharField(help_text='Serial number must be exactly 13 digits', max_length=13, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_sn', message='SN must be exactly 13 digits', regex='^\\d{13}$')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the task', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='result',
            field=models.TextField(blank=True, default='Action Not Yet Done', help_text='Result of the task', null=True),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('SN',), name='unique_sn'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('SN__regex', '^\\d{13}$')), name='check_sn_digits'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('location',), name='unique_location'),
        ),
    ]
