# Generated by Django 5.1.3 on 2024-11-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product_management",
            "0006_remove_product_id_task_note_alter_product_sn_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="location",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                fields=("rack", "layer", "space"),
                name="unique_location_rack_layer_space",
            ),
        ),
    ]
